import Head from 'next/head'
import Image from 'next/image'
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import CssBaseline from "@mui/material/CssBaseline";
import TextField from "@mui/material/TextField";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";

import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Link from 'next/link';



function Copyright(props) {
	return (
		<Typography
			variant="body2"
			color="text.secondary"
			align="center"
			{...props}
		>
			{"Copyright © "}
			<Link color="inherit" href="https://mui.com/">
				Your Website
			</Link>{" "}
			{new Date().getFullYear()}
			{"."}
		</Typography>
	);
}

const theme = createTheme();

export default function Home() {
    const handleSubmit = (event) => {
			event.preventDefault();
			const data = new FormData(event.currentTarget);
			console.log({
				email: data.get("email"),
				password: data.get("password"),
			});
		};
  return (
		<>
			<Head>
				<title>RideShare Admin</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ThemeProvider theme={theme}>
				<Container component="main" maxWidth="xs">
					<CssBaseline />
					<Box
						sx={{
							marginTop: 8,
							display: "flex",
							flexDirection: "column",
							alignItems: "center",
						}}
					>
						<Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>
							<LockOutlinedIcon />
						</Avatar>
						<Typography component="h1" variant="h5">
							RideShare Admin
						</Typography>
						<Box
							component="form"
							noValidate
							sx={{
								mt: 1,
								backgroundColor: "#2F58CD",
								paddingX: "2rem",
								paddingY: "4rem",
								borderRadius: "10px",
							}}
						>
							<TextField
								margin="normal"
								required
								fullWidth
								id="email"
								label="Enter Your ID"
								name="ID"
								type="text"
								autoFocus
								sx={{ backgroundColor: "white", borderRadius: "10px" }}
							/>
							<TextField
								margin="normal"
								required
								fullWidth
								name="password"
								label="Password"
								type="password"
								id="password"
								autoComplete="current-password"
								sx={{ backgroundColor: "white", borderRadius: "10px" }}
							/>
							<Link href="/Dashboard" style={{backgroundColor:"white",paddingBottom:15,borderRadius:3}}>
								<Button
									fullWidth
									variant="contained"
									sx={{ mt: 3, mb: 2, backgroundColor: "white", color: "black" }}
								>
									Sign In
								</Button>
							</Link>
						</Box>
					</Box>
					<Copyright sx={{ mt: 8, mb: 4 }} />
				</Container>
			</ThemeProvider>
		</>
	);
}
